In [1]:
import pandas as pd
import sqlite3

In [2]:
df = pd.read_csv(
    "data/Sample - Superstore.csv",
    encoding='latin1'
)

In [3]:
conn = sqlite3.connect("database/superstore.db")

In [4]:
df.to_sql(
    "superstore",
    conn,
    if_exists="replace",
    index=False
)

9994

In [5]:
pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

         name
0  superstore

In [26]:
#1.Total sales by category
query = """
SELECT Category, SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category;
"""

result = pd.read_sql(query, conn)
print(result)

          Category  Total_Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [16]:
#2.Top 5 products by profit
query = """
SELECT "Product Name",
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY "Product Name"
ORDER BY Total_Profit DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

                                        Product Name  Total_Profit
0              Canon imageCLASS 2200 Advanced Copier    25199.9280
1  Fellowes PB500 Electric Punch Plastic Comb Bin...     7753.0390
2               Hewlett Packard LaserJet 3310 Copier     6983.8836
3                 Canon PC1060 Personal Laser Copier     4570.9347
4  HP Designjet T520 Inkjet Large Format Printer ...     4094.9766

In [17]:
#3.Sales by region
query = """
SELECT Region,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

    Region  Total_Sales
0     West  725457.8245
1     East  678781.2400
2  Central  501239.8908
3    South  391721.9050

In [18]:
#4.Profit by category
query = """
SELECT Category,
       SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Category
ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Profit
0       Technology   145454.9481
1  Office Supplies   122490.8008
2        Furniture    18451.2728

In [19]:
#5.Customer segment by spending
query = """
SELECT Segment,
       SUM(Sales) AS Total_Spending
FROM superstore
GROUP BY Segment
ORDER BY Total_Spending DESC;
"""

pd.read_sql(query, conn)

       Segment  Total_Spending
0     Consumer    1.161401e+06
1    Corporate    7.061464e+05
2  Home Office    4.296531e+05

In [20]:
#6.Most Sold Sub-Categories
query = """
SELECT "Sub-Category",
       SUM(Quantity) AS Total_Quantity
FROM superstore
GROUP BY "Sub-Category"
ORDER BY Total_Quantity DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  Sub-Category  Total_Quantity
0      Binders            5974
1        Paper            5178
2  Furnishings            3563
3       Phones            3289
4      Storage            3158
5          Art            3000
6  Accessories            2976
7       Chairs            2356
8   Appliances            1729
9       Labels            1400

In [21]:
#7.Top 10 states by sales
query = """
SELECT State,
       SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

          State  Total_Sales
0    California  457687.6315
1      New York  310876.2710
2         Texas  170188.0458
3    Washington  138641.2700
4  Pennsylvania  116511.9140
5       Florida   89473.7080
6      Illinois   80166.1010
7          Ohio   78258.1360
8      Michigan   76269.6140
9      Virginia   70636.7200

In [22]:
#8.Avg discount by category
query = """
SELECT Category,
       AVG(Discount) AS Avg_Discount
FROM superstore
GROUP BY Category;
"""

pd.read_sql(query, conn)

          Category  Avg_Discount
0        Furniture      0.173923
1  Office Supplies      0.157285
2       Technology      0.132323

In [27]:
# 9.Technology Products (WHERE Clause)

query = """
SELECT *
FROM superstore
WHERE Category='Technology'
LIMIT 5;
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.152,6,0.2,90.7152
1,12,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.424,4,0.2,68.3568
2,20,CA-2014-143336,8/27/2014,9/1/2014,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.480,3,0.2,16.0110
3,27,CA-2016-121755,1/16/2016,1/20/2016,Second Class,EH-13945,Eric Hoffmann,Consumer,United States,Los Angeles,...,90049,West,TEC-AC-10003027,Technology,Accessories,Imation 8GB Mini TravelDrive USB 2.0 Flash Drive,90.570,3,0.0,11.7741
4,36,CA-2016-117590,12/8/2016,12/10/2016,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,75080,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544,7,0.2,123.4737

In [23]:
#10.Products with sales above Average
query = """
SELECT "Product Name", Sales
FROM superstore
WHERE Sales >
(
    SELECT AVG(Sales)
    FROM superstore
)
LIMIT 10;
"""

pd.read_sql(query, conn)

                                        Product Name      Sales
0                  Bush Somerset Collection Bookcase   261.9600
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...   731.9400
2      Bretford CR4500 Series Slim Rectangular Table   957.5775
3                     Mitel 5320 IP Phone VoIP phone   907.1520
4           Chromcraft Rectangular Conference Tables  1706.1840
5      Konftel 250 Conference phone - Charcoal black   911.4240
6        Fellowes PB200 Plastic Comb Binding Machine   407.9760
7  Stur-D-Stor Shelving, Vertical 5-Shelf: 72"H x...   665.8800
8      Bretford CR4500 Series Slim Rectangular Table  1044.6300
9  Riverside Palais Royal Lawyers Bookcase, Royal...  3083.4300

In [24]:
#11.Rank Products by Sales
query = """
SELECT
    "Product Name",
    Sales,

    RANK() OVER
    (
        ORDER BY Sales DESC
    ) AS Sales_Rank

FROM superstore
LIMIT 10;
"""

pd.read_sql(query, conn)

                                        Product Name      Sales  Sales_Rank
0  Cisco TelePresence System EX90 Videoconferenci...  22638.480           1
1              Canon imageCLASS 2200 Advanced Copier  17499.950           2
2              Canon imageCLASS 2200 Advanced Copier  13999.960           3
3              Canon imageCLASS 2200 Advanced Copier  11199.968           4
4              Canon imageCLASS 2200 Advanced Copier  10499.970           5
5   GBC Ibimaster 500 Manual ProClick Binding System   9892.740           6
6               Ibico EPK-21 Electric Binding System   9449.950           7
7   3D Systems Cube Printer, 2nd Generation, Magenta   9099.930           8
8  HP Designjet T520 Inkjet Large Format Printer ...   8749.950           9
9              Canon imageCLASS 2200 Advanced Copier   8399.976          10

In [25]:
#12.category Sales using CTE Requirement
query = """
WITH category_sales AS
(
    SELECT
        Category,
        SUM(Sales) AS Total_Sales
    FROM superstore
    GROUP BY Category
)

SELECT *
FROM category_sales;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [28]:
# 13.Categories with Sales Greater than 500000 (HAVING Clause)

query = """
SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM superstore
GROUP BY Category
HAVING Total_Sales > 500000;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330